### ISSUE TITLE
alexa-home node reconnection loop

### ISSUE THREAD

**Issue by M4dm4ni4c** [hardillb/node-red-contrib-alexa-home-skill#106]
Hi all, I hope I'm right here.

Running node-red 2.0.3 as a service on ioBroker with node-red-contrib-alexa-home-skill 0.1.19. skill on alexa alexa website is set up, account registered on https://alexa-node-red.bm.hardill.me.uk/. Everything seems to be working fine, even the node is running and receiving my voice commands. 

only one thing that keeps bothering me: the node  "alexa-home" constantly keeps switching between the states connected > disconnected > reconnecting > ...

No entries on ioBroker-Log or any messages in the debugging window of the node.

I could leave it as it is, since it seems to be running fine. But I don't want to create unnecessary network-traffic constantly pinging any service or server.

Any hints what/where to look at? Thanks guys.

**Comment by hardillb** [comment]
This will be because you have multiple config nodes (the bit where you entered your username/password). You should only have one of these shared between all the device nodes.

You can list the config nodes by selecting "Configuration nodes" from the hamburger menu in the top right hand corner of Node-RED. There should only be one `alexa-home-conf` node listed. If there is more than one, you need to delete all but, then go round all the device nodes and make sure the node is selected in the drop down.
