### ISSUE TITLE
Undefined payload received from alexa home node

### ISSUE THREAD

**Issue by mrohner** [hardillb/node-red-contrib-alexa-home-skill#11]
Hi,
I was very happy to find this extension to red-node. Unfortunately I have problems to check my Garage (door) status. I ask Alexa: "is my garage locked?". She says "checking" and then Hmm, the device does not respond". The node-red debug screen shows that I did not receive a valid payload from the alexa home node. Anyway I manage to trigger a http request and find the garage door is open. Again I do not know what to feed into the alexa home response node. I try to set an extra of UNLOCKED as described in your documentation , but the payload should be what exactly? Any help appreciated.
[https://www.dropbox.com/s/pxmh742isy0pj0o/Clipboard01.jpg?dl=0]

**Comment by hardillb** [comment]
Undefined is correct, because you have set the debug node to only show the msg.payload and there is no payload on a LockStateRequest message.

Going to need a fair bit more information here, the screen shot isn't all that useful.
What is the FULL message output from your last change nodes?

The message passed into the response node should look something like this:

{
   ...
  payload: true,
  extra: {
    lockState: "UNLOCKED"
  }
}

**Comment by mrohner** [comment]
Thanks for your explanations. I now changed the extract function to also generate this payload and feed it directly into the alexa response node. It now works correctly.

var data = JSON.parse(msg.payload);
msg.payload={};
msg.payload = data.result[0].Status;
if (msg.payload == "Open") {
    msg.payload = true;
    msg.extra = {
       lockState: "UNLOCKED"
    }
  }
 else {
     msg.payload = true;
     msg.extra = {
       lockState: "LOCKED"
    }
  }
return [msg];
