### ISSUE TITLE
Alexa home response not working

### ISSUE THREAD

**Issue by DaveTiff** [hardillb/node-red-contrib-alexa-home-skill#122]
Hi I have tried many combinations of code and I can get Alexa to control my Thermostat in Home Assistant but I cant get Alexa to respond.

I have tried the the Code form the [https://alexa-node-red.bm.hardill.me.uk/docs](url) but she replies "I am not quite sure whet went wrong"

![image](https://user-images.githubusercontent.com/25724769/143686176-fa67bac4-63d5-473f-8491-d95bd39f7c8d.png)

my code in Function node is:-

```
if (msg.payload < 10 || msg.payload > 30) {
    var range = {
        min: 10.0,
        max: 30.0
    }
    msg.payload = false;
    msg.extra = range;
    
} else {
    msg.extra = {
        targetTemperature: {
            value: msg.payload
        }
    };
    msg.payload = true;
}
return msg;
```

my Debug output is:-
![image](https://user-images.githubusercontent.com/25724769/143686253-20af2da8-2034-41be-8896-f7bf57a83046.png)

what am I missing?

Regards Dave

**Comment by hardillb** [comment]
Something appears to have changed on Amazon's end because the test devices I have fail as well with the message "I'm not quite sure what went wrong", which is a totally useless error message from a debugging point of view.

This service is no longer being actively being developed and Amazon have even removed all access to the doc for the version of the API it was written against. I don't have the time (or the inclination as I have moved whole sale over to using Google Home f) to rewrite the whole service to use the newer version of the Home Skill API. So it looks like thermostat devices will have to stay broken unless Amazon revet what ever change they made that broke them.

**Comment by DaveTiff** [comment]
Ok, thanks, totally understand

Re Dave
