### ISSUE TITLE
Self host?

### ISSUE THREAD

**Issue by Swiftnesses** [hardillb/node-red-contrib-alexa-home-skill#58]
Hi,

Firstly, thank you for this amazing work - appreciate it.

Is it possible for me to host a version of this myself, on my own domain?

Many thanks.

**Comment by hardillb** [comment]
Short answer, no

Longer answer, yes but it would require a near rewrite as you can no longer deploy v2 skills.

Also what benefit is there in recreating it? It makes no sense to have multiple versions of the same skill in the Alexa catalog, you could run it permanently in testing mode so only you could see it but then you have all the expense of hosting it. I really don't see a compelling argument for it which is why delberatly there are no set up instructions

**Comment by acalatrava** [comment]
> Also what benefit is there in recreating it?

What about security? I'm new to Alexa developing so I'm not sure how is the command flow but I guess that since you are running the backend, you have the ability to (theoretically) remote control all the devices of all your users?
I understand that turning on/off lights or even curtains are not a huge risk, but remotely triggering door locks is another story... This is why I would love to self hosting it too...

Also, thank you very much for your hard work... it is really amazing!

**Comment by hardillb** [comment]
Yes, in theory I could turn your devices on/off but I have no incentive to do so and you gave up on the security side of things the moment you plugged the Alexa device in.
