### ISSUE TITLE
Frequent disconnects and re-connects 0.1.17

### ISSUE THREAD

**Issue by smolvik1** [hardillb/node-red-contrib-alexa-home-skill#69]
Experiencing frequent disconnect and re-connects. 
This was working flawlessly on my previous Hass.IO installation on a RPi 3B+. After upgrading to an RPi 4 moving my configs over, I am now noticing these disconnects all the time. 

From the logs:
[error] [alexa-home-conf:3ef149fd.bd6116] Error: connect ECONNREFUSED 34.240.81.189:8883

**Comment by hardillb** [comment]
Ignore the connection refused error it's will use the fallback port in 5 seconds.

The repeated disconnect/reconnect is because you have multiple instances using the same credentials. This is not allowed, you can only have 1.

You have either

 1. 2 separate Node-RED instances.
 2. multiple copies of the config node in the same Node-RED instance.

Node-RED will show you all the config nodes by clicking on the top right menu and selecting "Configuration nodes".

If this used to work on a different instance make sure you delete the config node from the old instance as well as all the device nodes.

**Comment by daknightuk** [comment]
I had this exact issue, although I could not find any logs thanks for sharing the fix @hardillb
